import catalogData from '../../../public/data/catalog.json';

type CatalogItem={id:number;name:string;tcg?:{variants?:{id:number}[];tags?:{labels?:string[];slot?:string;combatStyle?:string}}};
const categories=[['currency','Currency'],['teleports','Teleports'],['food_potions','Food & potions'],['clues_uniques','Clues & uniques'],['slayer_pvm','Slayer & PvM'],['runes_magic','Runes & magic'],['seeds_farming','Seeds & farming'],['herblore','Herbs & Herblore'],['ores_bars','Ores & bars'],['logs_planks','Logs & planks'],['prayer','Prayer'],['fletching','Fletching'],['crafting','Crafting materials'],['weapons_ammo','Weapons & ammunition'],['armour_equipment','Armour & equipment'],['tools_skilling','Tools & skilling'],['miscellaneous','Miscellaneous']] as const;
const normal=(v:string)=>(v||'').trim().toLowerCase().replace(/\s+/g,' ');
function classify(item:CatalogItem){const name=normal(item.name),tags=new Set(item.tcg?.tags?.labels||[]),slot=item.tcg?.tags?.slot;if(tags.has('Currency'))return'currency';if(/teleport|tablet|teletab|fairy ring|games necklace|dueling ring/.test(name))return'teleports';if(/potion|brew|restore|serum|antipoison|antidote|food|cake|pie|pizza|stew|kebab|wine|beer|ale/.test(name))return'food_potions';if(tags.has('Clue')||tags.has('Pet'))return'clues_uniques';if(tags.has('Slayer'))return'slayer_pvm';if(tags.has('Runecraft')||name.endsWith(' rune')||name.includes('rune essence'))return'runes_magic';if(name.includes('seed')||tags.has('Farming'))return'seeds_farming';if(tags.has('Herblore'))return'herblore';if(name.includes('ore')||name.endsWith(' bar')||(tags.has('Mining')&&!slot))return'ores_bars';if(name.includes('log')||name.includes('plank')||tags.has('Woodcutting')||tags.has('Firemaking'))return'logs_planks';if(tags.has('Prayer'))return'prayer';if(tags.has('Fletching'))return'fletching';if(tags.has('Crafting')&&!slot)return'crafting';if(tags.has('Weapon')||tags.has('Ammo')||item.tcg?.tags?.combatStyle)return'weapons_ammo';if(tags.has('Equipment')||slot)return'armour_equipment';if(tags.has('Tool')||['Agility','Construction','Cooking','Fishing','Hunter','Sailing','Smithing','Thieving'].some(t=>tags.has(t)))return'tools_skilling';return'miscellaneous'}
const idsFor=(items:CatalogItem[])=>Array.from(new Set(items.flatMap(i=>[i.id,...(i.tcg?.variants||[]).map(v=>v.id)]))).sort((a,b)=>a-b);
function decodeIds(value:string){let current=0;const ids=new Set<number>();for(const part of value.split('.')){if(!/^[0-9a-z]+$/.test(part))throw new Error('Invalid collection state');current+=parseInt(part,36);ids.add(current)}return ids}
function block(state:'obtained'|'missing',id:string,label:string,items:CatalogItem[]){const macro=`${state}_${id}`.toUpperCase(),ids=idsFor(items),color=state==='obtained'?'#FF62E6A7':'#FFFF8787';return `/*@ define:input:cardcore_${state}\ntype: style\nlabel: "${label}"\ngroup: "${label} (${items.length} cards / ${ids.length} item IDs)"\nexampleItem: "${(items[0]?.name||'Coins').replaceAll('"',"'")}"\n*/\n#define VAR_CARDCORE_${macro}_STYLE hidden = false; textColor = "${color}"; borderColor = "${color}"; showLootbeam = ${state==='obtained'?'true':'false'}; notify = false; showValue = true; menuSort = ${state==='obtained'?150:50};\n#define CONST_CARDCORE_${macro}_IDS [${ids.join(',')}]\nrule (id:CONST_CARDCORE_${macro}_IDS) { VAR_CARDCORE_${macro}_STYLE }`}
export async function GET(request:Request){try{const url=new URL(request.url),encoded=url.searchParams.get('ids')||'',name=(url.searchParams.get('name')||'My Collection').slice(0,80).replaceAll('"',"'"),owned=decodeIds(encoded),items=(catalogData.items as CatalogItem[]),obtained=items.filter(i=>owned.has(i.id)),missing=items.filter(i=>!owned.has(i.id)),blocks=(state:'obtained'|'missing',list:CatalogItem[])=>categories.map(([id,label])=>block(state,id,label,list.filter(i=>classify(i)===id))).join('\n\n');const filter=`/*@ define:module:cardcore_obtained\nname: "Cardcore: Obtained Cards"\nsubtitle: "${obtained.length} cards unlocked by this collection"\n*/\nmeta {\n name = "Cardcore - ${name}";\n description = "Personalized Cardcore filter generated from an OSRS TCG collection.";\n}\n${blocks('obtained',obtained)}\n\n/*@ define:module:cardcore_missing\nname: "Cardcore: Missing Cards"\nsubtitle: "${missing.length} cards not yet obtained"\nenabled: false\n*/\n${blocks('missing',missing)}\n`;return new Response(filter,{headers:{'Content-Type':'text/plain; charset=utf-8','Access-Control-Allow-Origin':'*','Cache-Control':'public, max-age=300'}})}catch(error){return Response.json({error:error instanceof Error?error.message:'Invalid collection state'},{status:400,headers:{'Access-Control-Allow-Origin':'*'}})}}
